services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    restart: unless-stopped

  api:
    environment:
      - APP_PORT=:3000
      - PUBLIC_HOST=orangeurl.live
      - DOMAIN=https://orangeurl.live
      - API_QUOTA=10
      - DB_ADDR=db:6379
      - DB_PASS=
    build: api
    expose:
      - "3000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: unless-stopped
