app = "orangeurl"
primary_region = "bom"

[build]
  context = "api"
  dockerfile = "Dockerfile"

[env]
  APP_PORT = ":3000"
  DOMAIN = "https://orangeurl.fly.dev"
  API_QUOTA = "10"

[http_service]
  internal_port = 3000
  force_https = true